name: Create release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  create-release:
    name: Create release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          name: Release ${{github.ref_name}}

  release-application:
    name: Release application
    needs: create-release
    permissions:
      contents: write
    uses: ./.github/workflows/release-application.yml
