name: Release ZIP

on:
  release:
    types: [created]

jobs:
  publish:
    name: Publish
    runs-on: macos-11
    env:
      BIN_NAME: dupeguru-reference-modifier
      APP_NAME: dupeGuru Reference Modifier
      PKG_ID: io.leoliu.dupeguru.reference-modifier
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Prepare environment
        uses: actions/setup-go@v2
        with:
          go-version: "^1.17"
      - name: Build binary
        run: |
          GOARCH=amd64 go build \
            -o ${{env.BIN_NAME}}-amd64 \
            -ldflags="""
              -X 'main.linkApplicationName=${{env.APP_NAME}}' \
            """
          GOARCH=arm64 go build \
            -o ${{env.BIN_NAME}}-arm64 \
            -ldflags="""
              -X 'main.linkApplicationName=${{env.APP_NAME}}' \
            """
      - name: Build macOS application
        run: |
          mkdir -p ${{env.APP_NAME}}.app/Contents/MacOS
          mkdir -p ${{env.APP_NAME}}.app/Contents/Resources
          echo """
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
            <key>CFBundleName</key>
            <string>${{env.APP_NAME}}</string>
            <key>CFBundleIdentifier</key>
            <string>${{env.PKG_ID}}</string>
            <key>CFBundleExecutable</key>
            <string>${{env.BIN_NAME}}</string>
            <key>CFBundleShortVersionString</key>
            <string>$(sed -re 's|$v||' <<< ${{github.event.release.tag_name}})</string>
            <key>CFBundleVersion</key>
            <string>$(sed -re 's|$v||' <<< ${{github.event.release.tag_name}}).$(date +%s)</string>
          </dict>
          </plist>
          """ > ${{env.APP_NAME}}.app/Contents/Info.plist
          mkdir amd64 arm64
          cp ${{env.APP_NAME}}.app amd64
          cp ${{env.BIN_NAME}}-amd64 amd64/${{env.APP_NAME}}.app/Contents/MacOS/${{env.BIN_NAME}}
          cp ${{env.APP_NAME}}.app arm64
          cp ${{env.BIN_NAME}}-arm64 arm64/${{env.APP_NAME}}.app/Contents/MacOS/${{env.BIN_NAME}}
      - name: Build ZIP
        run: |
          zip -r ${{env.APP_NAME}}-amd64.zip amd64/${{env.APP_NAME}}.app
          zip -r ${{env.APP_NAME}}-arm64.zip arm64/${{env.APP_NAME}}.app
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{env.APP_NAME}}.zip
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB}}
